/*
HORSE RACE
*/


rule "set up world"
    when
        $startupevent : Event(id == "Startup")
    then
        Room startfinish = new Room(-9, 89, 189, -2, 95, 184, "StartFinish");
        insert(startfinish);
        
        Room checkpointone = new Room(32, 89, 184, 37, 100, 190, "CheckPointOne");
        insert(checkpointone);

        Room checkpointtwo = new Room(32, 89, 159, 38, 100, 154, "CheckPointTwo");
        insert(checkpointtwo);

        Room checkpointthree = new Room(-21, 89, 159, -26, 100, 153, "CheckPointThree");
        insert(checkpointthree);

        Room checkpointfour = new Room(-21, 89, 184, -27, 100, 189, "CheckPointFour");
        insert(checkpointfour);
        
        Team burgerbaby = new Team("BurgerBaby");
        insert(burgerbaby);

        Team numberOne = new Team ("NumberOne");
        insert (numberOne);

       Room stables = new Room(3, 89, 197, -11, 96, 191, "Stables");
       insert(stables);

        Event greetPlayer = new Event("greetPlayer");
        insert(greetPlayer);

end

rule "spawning horses"
    when
        $player : Player()
        $room : Room(id == "Stable 2" && playersInRoom contains $player.getName())
        $team : Team(id == "NumberOne" && points == 0)
    then
        cmds.notifyChat("Contestants, please mount your horses!");
    end
       
rule "Announcer"
    when
        $greetPlayer : Event(id == "greetPlayer" && !hasFired)
        $player : Player()
        $team : Team(id == "NumberOne" && points == 0)
        $room : Room(id == "StartFinish" && playersInRoom contains $player.getName())
    then
        cmds.notifyChat("Welcome to the annual horse race of Tergl Squub!"); 
        modify($greetPlayer){setHasFired(true)}
        //modify($greetPlayer){setHasFired(false)}
    end

rule "first checkpoint"
        when
            $player : Player()
            $team : Team(id == "NumberOne" && points == 0)
            $room : Room(id == "CheckPointOne" && playersInRoom contains $player.getName())
        then
            cmds.notifyChat("Contestant number One has entered CheckPoint number one!");
            modify($team) { setPoints($team.getPoints() + 1) }
            cmds.notifyChat("Team Number One has " + $team.getPoints() + " points!");
           end

rule "second checkpoint"
        when
            $player : Player()
            $team : Team(id == "NumberOne" && points == 1)
            $room : Room(id == "CheckPointTwo" && playersInRoom contains $player.getName())
        then
            cmds.notifyChat("Contestant number One has entered CheckPoint number two!");
            
            modify($team) { setPoints($team.getPoints() + 1) }
            cmds.notifyChat("Team Number One has " + $team.getPoints() + " points!");
        end

rule "third checkpoint"
        when
            $player : Player()
            $team : Team(id == "NumberOne" && points == 2)
            $room : Room(id == "CheckPointThree" && playersInRoom contains $player.getName())
        then
            cmds.notifyChat("Contestant number One has entered CheckPoint number three!");
            
            modify($team) { setPoints($team.getPoints() + 1) }
            cmds.notifyChat("Team Number One has " + $team.getPoints() + " points!");
        end

rule "fourth checkpoint"
        when
            $player : Player()
            $team : Team(id == "NumberOne" && points == 3)
            $room : Room(id == "CheckPointFour" && playersInRoom contains $player.getName())
        then
            cmds.notifyChat("Contestant number One has entered CheckPoint number four!");
            
            modify($team) { setPoints($team.getPoints() + 1) }
            cmds.notifyChat("Team Number One has " + $team.getPoints() + " points!");
        end

rule "finishing the race"
    when
        $player : Player()
        $team : Team(id == "NumberOne" && points == 4)
        $room : Room(id == "StartFinish" && playersInRoom contains $player.getName())
    then
        cmds.notifyChat("Team number One has won with four points!");
    end

rule "restarting"
    when
        $player : Player()
        $team : Team(id == "NumberOne" && points == 4)
        $room : Room(id == "StartFinish" && playersInRoom contains $player.getName())
    then
        cmds.notifyChat("We are now restarting the race.");
        modify($team) { setPoints(0) }
    end

rule "Print mobs in rooms"
    when
        $player : Player()
        $mob : Mob(type == Mob.MobTypes.HORSE)
        $room : Room(id == "Stables" && playersInRoom contains $player.getName() && mobsInRoom.containsKey($mob.getId()))
        $greetPlayer : Event(id == "greetPlayer" && !hasFired)
    then
        modify($greetPlayer){setHasFired(true)}
        cmds.notifyChat("Contestants, please mount your steeds!");
end
