package com.example
 
import org.drools.minecraft.model.Room;
import org.drools.minecraft.model.Session;
import org.drools.minecraft.model.Player;
import org.drools.minecraft.model.Inventory;
import org.drools.minecraft.model.Item;
import org.drools.minecraft.util.DroolsCommandInterface;
import org.drools.minecraft.util.DroolsTestInterface;

rule "Setup"
    when
        //I'm a stub!
    then
        //I'm the continuation of a stub!
end


rule "Update"
no-loop
    when
        //I'm a stub, and maybe should go away entirely!
    then
        //I'm still a stub!
        
end


rule "modifyInventory"
    when
        $i : Inventory()
    then
        System.out.println("ModifyInventory base");
        for(Item item : $i.getItems())
            {
                System.out.println("ModifyInventory: " + item.getType());
            }
        
end

rule "Open the door when the player has the key"
    when
        $r : Room(id == "LighthouseDoor")
        $p : Player(roomsIn.contains($r))
        Item(type == "item.key") from $p.getInventory().getItems()
        
    then
        System.out.println("Player has key.");
        DroolsCommandInterface.modifyBlocks(-85, 76, 437, -84, 79, 437, $r.getDimension(), DroolsCommandInterface.Blocks.Air);
       
end

