package com.example
 
import org.drools.minecraft.model.Room;
import org.drools.minecraft.model.Session;
import org.drools.minecraft.model.Player;

rule "Setup"
    when
        //I'm a stub!
    then
        //I'm a stub, too!
end


rule "Update"
no-loop
    when
        //I'm a stub, and maybe should go away entirely!
    then
        //I'm still a stub!
        
end

rule "RoomExists"
    when
        room : Room()
    then
        System.out.println("There is a room at: " + room.getX() + ", " +room.getY() + ", " +room.getZ() + ", " +room.getFx() + ", " +room.getFy() + ", " +room.getFz());
end

/**
Note: this shouldn't fire unless we insert the player with the session.
*/
rule "PlayerExists"
    when
        player : Player()
    then
        System.out.println("There is a player.");
end

rule "SessionExists"
    when
        session : Session()
    then
        System.out.println("There is a session.");
end