package com.example
 
import org.drools.minecraft.model.Room;
import org.drools.minecraft.model.Session;
import org.drools.minecraft.model.DroolsPlayer;
import org.drools.minecraft.model.Inventory;
import org.drools.minecraft.model.Item;
import org.drools.minecraft.util.DroolsCommandInterface;
import org.drools.minecraft.util.DroolsTestInterface;

rule "Setup"
    when
        //I'm a stub!
    then
        //I'm the continuation of a stub!
end


rule "Update"
no-loop
    when
        //I'm a stub, and maybe should go away entirely!
    then
        //I'm still a stub!
        
end


rule "modifyInventory"
    when
        inventory : Inventory()
    then
        System.out.println("ModifyInventory base");
        for(Item item : inventory.getItems())
            {
                System.out.println("ModifyInventory: " + item.getType());
            }
        
end

rule "goThroughLighthouseDoor"
    when
        room : Room(id.equals("LighthouseDoor"))
        player : DroolsPlayer()
    then
        if(room != null && player != null)
        {
                if(DroolsTestInterface.playerHasItem(player, "item.key") && DroolsTestInterface.playerInRoom(player, room))
                {
                    System.out.println("Player has key.");
                    DroolsCommandInterface.ModifyBlocks(-85, 76, 437, -84, 79, 437, room.getDimension(), DroolsCommandInterface.Blocks.Air);
                }
        }
end

