package com.example
 
import org.drools.minecraft.model.*;
import org.drools.minecraft.model.Event;
import org.drools.minecraft.helper.CommandHelper;
import org.drools.minecraft.helper.TestHelper;
import java.util.*;


import java.util.ArrayList;

global CommandHelper cmds;
global TestHelper    tests;


rule "set up world"
    when
        $startupevent: Event(id == "Startup")
    then
        Chest chest = new Chest("Flag Chest", new Location(182, 94, -276));
        insert(chest);
        cmds.notifyGenerateChest(chest);
        BaseItem flag = new BaseItem("Flag", "banner");
	cmds.notifyItemToChest(chest, flag);

        Room scorezone_red = new Room(155, 94, -280, 151, 99, -272, "Scorezone_Red");
        insert(scorezone_red);

        Room scorezone_blue = new Room(209, 94, -272, 213, 99, -280,  "Scorezone_Blue");
        insert(scorezone_blue);
        
        insert(new NamedLocation(153, 98, -275, "Redspawn"));
        insert(new NamedLocation(211, 97, -275, "Bluespawn"));

        Room chasm = new Room(141, 80, -310, 260, 62, -199, "Chasm");
        insert(chasm);
        
        insert(new Team("red"));
        insert(new Team("blue"));

        
end

rule "Give red a point when the flag enters the blue scorezone"
    when
        $teamred : Team(id == "red")
        $player : Player($teamred.contains($player.getName()))
        $flag : BaseItem(name == "Flag") from $player.getInventory()
        $r: Room(id == "Scorezone_Blue" && playersInRoom contains $player.getName())
        $spawnred : NamedLocation(name == "Redspawn")
        $chest : Chest(name == "Flag Chest")
    then
        $teamred.setPoints($teamred.getPoints() + 1);
        cmds.notifyTeleportPlayer($player, $spawnred);
        cmds.notifyClearPlayerInventory($player);
        
        BaseItem flag = new BaseItem("Flag", "banner");
	cmds.notifyItemToChest($chest, flag);
        
        cmds.notifyChat("Scooooorrrre! Red now has " + $teamred.getPoints() + " points!");
        cmds.notifyChat("Test text, dude!", $player);
        System.out.println("Someone stepped in the blue scorezone");
end

rule "Give blue a point when the flag enters the red scorezone"
    when
        $teamblue : Team(id == "blue")
        $player : Player($teamblue.contains($player.getName()))
        $flag : BaseItem(name == "Flag") from $player.getInventory()
        $r: Room(id == "Scorezone_Red" && playersInRoom contains $player.getName())
        $spawnblue : NamedLocation(name == "Bluespawn")
        $chest : Chest(name == "Flag Chest")
    then
        $teamblue.setPoints($teamblue.getPoints() + 1);
        cmds.notifyTeleportPlayer($player, $spawnblue);
        cmds.notifyClearPlayerInventory($player);
        
        BaseItem flag = new BaseItem("Flag", "banner");
	cmds.notifyItemToChest($chest, flag);
        
	System.out.println("Someone stepped in the red scorezone with the flag");
        cmds.notifyChat("Test text, dude!", $player);
        cmds.notifyChat("Scooooorrrre! Blue now has " + $teamblue.getPoints() + " points!");
end

rule "Teleport a player who hits the chasm with the flag"
    when
        $player : Player()
        $teamred : Team(id == "red")
        $teamblue : Team(id == "blue")
        $spawnred : NamedLocation(name == "Redspawn")
        $spawnblue : NamedLocation(name == "Bluespawn")
        $r: Room(id == "Chasm", playersInRoom contains $player.getName())
        BaseItem(name == "Flag") from $player.getInventory()
        $chest : Chest(name == "Flag Chest")
    then
        if($teamred.contains($player.getName()))
        {
            cmds.notifyTeleportPlayer($player, $spawnred);
        }else if($teamblue.contains($player.getName()))
        {
            cmds.notifyTeleportPlayer($player, $spawnblue);
        }
        cmds.notifySetPlayerHealth($player, 20);
        cmds.notifyClearPlayerInventory($player);
        cmds.notifyEffectPlayer($player, CommandHelper.Effect.SPEED, 600, 3);
        cmds.notifyEffectPlayer($player, CommandHelper.Effect.JUMP_BOOST, 600, 3);
        
        BaseItem flag = new BaseItem("Flag", "banner");
	cmds.notifyItemToChest($chest, flag);
        
        System.out.println("Someone fell into the chasm with the flag");
end

rule "Teleport a player who hits the chasm"
    when
        $player : Player()
        $teamred : Team(id == "red")
        $teamblue : Team(id == "blue")
        $spawnred : NamedLocation(name == "Redspawn")
        $spawnblue : NamedLocation(name == "Bluespawn")
        $r: Room(id == "Chasm", playersInRoom contains $player.getName())
        not BaseItem(name == "Flag") from $player.getInventory()
    then
        if($teamred.contains($player.getName()))
        {
            cmds.notifyTeleportPlayer($player, $spawnred);
        }else if($teamblue.contains($player.getName()))
        {
            cmds.notifyTeleportPlayer($player, $spawnblue);
        }
        cmds.notifySetPlayerHealth($player, 20);
        cmds.notifyEffectPlayer($player, CommandHelper.Effect.SPEED, 600, 3);
        cmds.notifyEffectPlayer($player, CommandHelper.Effect.JUMP_BOOST, 600, 3);
	System.out.println("Someone fell into the chasm");
end

rule "If a player has no team, assign him one."
    when
        $teamred : Team(id == "red")
        $teamblue : Team(id == "blue")
        $p : Player(!($teamred contains $p.getName() || $teamblue contains $p.getName()))
    then    
        if($teamred.size() <= $teamblue.size())
        {
            $teamred.add($p.getName());
            cmds.notifyChat("Added player " + $p.getName() + " to team red!");
        }else
        {
            $teamblue.add($p.getName());
            cmds.notifyChat("Added player " + $p.getName() + " to team blue!");
        }
        
        cmds.notifyTeleportPlayer($p, new Location(182, 96, -276));
end































