package com.example
 
import org.drools.minecraft.model.*;
import org.drools.minecraft.model.Event;
import org.drools.minecraft.helper.CommandHelper;
import org.drools.minecraft.helper.TestHelper;


import java.util.ArrayList;

global CommandHelper cmds;
global TestHelper    tests;

/*
rule "Setup"
    when
        $startup : Event(id == "Setup" && !hasFired)
    then
        //ArrayList<InventoryItem> chestContents = new ArrayList<InventoryItem>();
        //chestContents.add(new Key("key", 1));
        //chestContents.add(new BaseItem("bread", 12));
        
        //DroolsCommandInterface.placeChest(-91, 64, 433, 0, chestContents);
        $startup.setHasFired(true);
end

rule "Open the door when the player has the key"
    when
        $d : Door(id == "ToRoomB")
        $p : Player(DroolsTestInterface.playerTouchingDoor($p, $d))
        Item(type == "item.key") from $p.getInventory()
        
    then
		$d.setOpen(true);
		cmds.notifyOpenDoor($d);

end

rule "Close the door when we're not around."
    when
        $d : Door(id == "LighthouseDoor")
        $p : Player(!DroolsTestInterface.playerTouchingDoor($p, $d))
        
    then
		$d.setOpen(false);
		cmds.notifyCloseDoor($d);

end

*/

rule "show content of the room where the player is"
    when
        $p: Player()
        $r: Room(playersInRoom contains $p.getName())
    then
        for(WorldItem i : $r.getItems()){
            System.out.println(">>> Item: "+ i);
        }

        for(InventoryItem i : $p.getInventory()){
            System.out.println(">>> Inventory Item: "+ i);
        }
end

rule "Open the door when the player has the key matching that Door"
    when
        $p : Player()
        Key() from $p.getInventory()
        $d : Door(id == "ToRoomB", open == false)
        $r: Room(playersInRoom contains $p.getName(), doors contains $d)
        
        
    then    
       /*modify($d){
         setOpen(true);
       }
       cmds.openDoor($d);*/
		$d.setOpen(true);
		cmds.notifyOpenDoor($d);

end