package com.example
 
import com.example.examplemod.ExampleMod.Message;
import com.example.droolsinterface.DroolsWorldState;
import com.example.droolsinterface.DroolsTestInterface;
 
rule "Hello World"
    when
        m : Message( status == Message.HELLO, myMessage : message )
    then
        System.out.println( myMessage );
        m.setMessage( "Goodbye cruel world" );
        m.setStatus( Message.GOODBYE );
        update( m );
end

rule "GoodBye"
    when
        Message( status == Message.GOODBYE, myMessage : message )
    then
        System.out.println( myMessage );
end

rule "BindPlayer"
    when
        $state : DroolsWorldState()
        $player : state.players.get(0);
        DroolsTestInterface.withinPos($player, -100, -100, -100, 100, 100, 100)
    then
        System.out.println( "WITHIN!" );
end
