package com.example
 
import com.example.droolsinterface.DroolsPlayerPos;
import com.example.droolsinterface.DroolsTestInterface;
import com.example.droolsinterface.DroolsCommandInterface;


rule "BindPlayer"
    when
        pos : DroolsPlayerPos(x >= 100 || x <= -100 || z >= 100 || z <= -100)
    then
        System.out.println( "Player exceeded game bounds! Move him!" );
        DroolsCommandInterface.movePlayer(pos.player, 0, 40, 0);
end
